name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

    - name: Decode and Save EC2 SSH Private Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 -d > private_key.pem
        chmod 600 private_key.pem

    - name: SSH and deploy Docker container
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 --decode > private_key.pem
        chmod 600 private_key.pem

        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          docker pull uzzi001/react-app:latest

          # Stop and remove existing container
          docker stop react_app || true
          docker rm react_app || true

          # Run new container on port 80
          docker run -d --name react_app -p 80:80 --restart always uzzi001/react-app:latest
        EOF
